### ISSUE TITLE
Express backend architectuur

### ISSUE THREAD

**Issue by Pjiwm** [Pjiwm/circle-project#11]
Dit gaat enkel over de applicatie achitectuur.
- [ ] ~RSA utils~ **Zie Issue:** #35 
- [x] Router
- [ ] ~Models~ **Zie Issue:** #32 
- [x] Controller
- [ ] ~Database connectie~ **Zie Issue:** #31
